apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    azure:
      storage:
        storageAccountName: jxgladsculpin
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    environmentGitOwner: msh-jx-1
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: aks
    registry: gladsculpin.azurecr.io
  environments:
  - key: dev
    owner: msh-jx-1
    repository: Cluster
  - key: staging
  - key: production
  ingress:
    domain: 20.81.66.244.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: msh-bot-1
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: azblob://logs
  terraformVault: true
  vault: {}
  webhook: lighthouse
