# Source: cd-indicators/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cd-indicators
  labels:
    app.kubernetes.io/name: cd-indicators
    app.kubernetes.io/instance: "cd-indicators"
    helm.sh/chart: cd-indicators-0.0.13
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: postgresql-host
      key: secret/data/cd/indicators
      property: postgresql-host
    - name: postgresql-port
      key: secret/data/cd/indicators
      property: postgresql-port
    - name: postgresql-database
      key: secret/data/cd/indicators
      property: postgresql-database
    - name: postgresql-username
      key: secret/data/cd/indicators
      property: postgresql-username
    - name: postgresql-password
      key: secret/data/cd/indicators
      property: postgresql-password
    - name: grafana-datasource-postgresql-json-data
      key: secret/data/cd/indicators
      property: grafana-datasource-postgresql-json-data
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'cd-indicators'
      labels:
        app.kubernetes.io/name: cd-indicators
        app.kubernetes.io/instance: "cd-indicators"
        helm.sh/chart: cd-indicators-0.0.13
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: "Helm"
