# Source: loki/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: loki
  namespace: jx-observability
  labels:
    app: loki
    chart: loki-2.5.0
    release: loki
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: loki.yaml
      key: secret/data/loki
      property: loki.yaml
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'loki'
      labels:
        app: loki
        chart: loki-2.5.0
        release: loki
        heritage: Helm
